version: 0.2

env:
  variables:
    IMAGE_TAG: "latest"

phases:
  install:
    runtime-versions:
      docker: 20

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URI
      - chmod +x ./simple-app/gradlew     # ✅ Make gradlew executable
      - cd simple-app
      - echo "Running Gradle build..."
      - ./gradlew build
      - cd ..

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $ImageName:$IMAGE_TAG -f simple-app/Dockerfile simple-app

  post_build:
    commands:
      - echo "Tagging image..."
      - docker tag $ImageName:$IMAGE_TAG $ECR_URI/$ImageName:$IMAGE_TAG
      - echo "Pushing image to ECR..."
      - docker push $ECR_URI/$ImageName:$IMAGE_TAG

artifacts:
  files:
    - '**/*'