version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Gradle...
      - cd simple-app
      - chmod +x gradlew

  pre_build:
    commands:
      - echo Building the JAR...
      - cd simple-app
      - ./gradlew build

  build:
    commands:
      - echo Building Docker image...
      - cd simple-app
      - docker build -t $ImageName .

  post_build:
    commands:
      - echo Tagging image...
      - docker tag $ImageName:latest $ECR_URI/$ImageName:latest
      - echo Pushing image to ECR...
      - docker push $ECR_URI/$ImageName:latest

artifacts:
  files:
    - simple-app/build/libs/*.jar
