version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - ls
      - echo Installing dependencies...
      - chmod +x gradlew

  pre_build:
    commands:
      - echo Logging in to ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_URI
      - echo Building JAR...
      - ./gradlew build
      - ls -l build/libs

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ImageName .

  post_build:
    commands:
      - echo Tagging image...
      - docker tag $ImageName:latest $ECR_URI/$ImageName:latest
      - echo Pushing image to ECR...
      - docker push $ECR_URI/$ImageName:latest

artifacts:
  files:
    - build/libs/*.jar
