version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies..."

  pre_build:
    commands:
      - echo "Preparing to build..."
      - cd simple-app
      - chmod +x gradlew

  build:
    commands:
      - echo "Starting gradle build..."
      - ./gradlew build
      - echo "Building Docker image..."
      - docker build -t $ImageName .

  post_build:
    commands:
      - echo "Tagging image..."
      - docker tag $ImageName:latest $ECR_URI/$ImageName:latest
      - echo "Pushing image to ECR..."
      - docker push $ECR_URI/$ImageName:latest

artifacts:
  files:
    - simple-app/build/libs/*.jar
