version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URI
      - chmod +x ./simple-app/gradlew   # ✅ Fix permission
      - cd simple-app
      - echo "Starting gradle build..."
      - ./gradlew build
      - cd ..

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ImageName:latest -f simple-app/Dockerfile simple-app

  post_build:
    commands:
      - echo "Tagging and pushing image to ECR..."
      - docker tag $ImageName:latest $ECR_URI/$ImageName:latest
      - docker push $ECR_URI/$ImageName:latest

artifacts:
  files:
    - '**/*'